if (${CMAKE_SYSTEM_NAME} MATCHES "Linux")
    set(Ice_SLICE_DIR /usr/share/ice/slice)
elseif (${CMAKE_SYSTEM_NAME} MATCHES "Darwin")
    set(Ice_SLICE_DIR /usr/local/Cellar/ice/3.7.0/share/ice/slice)
endif()
FIND_PACKAGE(Ice 3.7 REQUIRED Ice)

#message("source= ${FILES_SLICE}, Ice_HOME=${Ice_SLICE_DIRS}")

IF(NOT("${FILES_SLICE}" STREQUAL ""))
    SET ( SLICE2CPP_COMMAND ${Ice_SLICE2CPP_EXECUTABLE})
    message("Ice_SLICE_DIRS=${Ice_SLICE_DIRS}, MODULE_SLICE_DIR=${MODULE_SLICE_DIR}")
    FOREACH(SOURCE_SLICE ${FILES_SLICE})
        SET(SOURCE_SLICE_FILENAME ${SOURCE_SLICE})
        STRING( REGEX REPLACE "\\.ice" .cpp SOURCE_OUTPUT_BASENAME
                "${SOURCE_SLICE}" )
        STRING( REGEX REPLACE "\\.ice" .h HEADER_OUTPUT_BASENAME
                "${SOURCE_SLICE}" )
        MESSAGE("icefile=${SOURCE_SLICE_FILENAME}")
        ADD_CUSTOM_COMMAND(
                OUTPUT ${SOURCE_OUTPUT_BASENAME} ${HEADER_OUTPUT_BASENAME}
                PRE_BUILD
                DEPENDS ${SOURCE_SLICE}
                COMMAND ${SLICE2CPP_COMMAND} ARGS    ${SOURCE_SLICE_FILENAME} -I${Ice_SLICE_DIRS} -I${MODULE_SLICE_DIR} --output-dir ${MODULE_SLICE_DIR}
#                COMMAND ${Ice_SLICE2JS_EXECUTABLE} ARGS ${SOURCE_SLICE_FILENAME} -I${Ice_SLICE_DIRS} -I${MODULE_SLICE_DIR} --output-dir ${MODULE_SLICE_DIR}
                COMMENT "${SLICE2CPP_COMMAND} -- Generating ${SOURCE_OUTPUT_BASENAME} ${HEADER_OUTPUT_BASENAME} file from ${SOURCE_SLICE}"
        )
        SET(SOURCES_SLICE ${SOURCES_SLICE} ${SOURCE_OUTPUT_BASENAME} ${HEADER_OUTPUT_BASENAME})
        SET(HEADERS_SLICE ${HEADERS_SLICE} ${HEADER_OUTPUT_BASENAME})
    ENDFOREACH(SOURCE_SLICE ${SOURCE_SLICE_FILENAME})
    INCLUDE_DIRECTORIES(${MODULE_SLICE_DIR})
ENDIF(NOT("${FILES_SLICE}" STREQUAL ""))